[package]
name = "bitfield-impl"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = {version="2.0.71", features=["full", "visit-mut"]}
quote = "1.0"
proc-macro2 = "1"

